### ISSUE TITLE
Missing events

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-event-manager#3]
Shouldn't you support  **keypress**?

And this? **copy**, **cut** and **paste**.

And I also notice you skipped events such as **mouseenter**. There are still use cases for even after IE9+

https://facebook.github.io/react/docs/events.html#supported-events

**Comment by jails** [comment]
I added a couple of missing common events https://github.com/crysalead-js/dom-event-manager/blob/master/index.js#L89-123. However you can support all events by adding them using `bind()`.
