### ISSUE TITLE
touch, blur, focus not working

### ISSUE THREAD

**Issue by ghost** [crysalead-js/dom-event-manager#5]
seems like touch are not working ? And also blur and focus event are not working correctly.

**Comment by jails** [comment]
this repo doesn't have any dist file but I copied/pasted all the library inside the fiddle http://jsfiddle.net/9o2axux6/ and touch event works as expected.

**Comment by marcorra** [comment]
I didn't get it to work, but I see touch is working now.
However, how are you triggering blur? I couldn't get that too work. And the focus lost issue in Firefox?
I looked at jQuery source for this, and but blur and focus get special treatment!

**Comment by marcorra** [comment]
I just found this issue because you are a huge inspiration for me, so I started to write my own library now. And I solved blur - focus events - like this:

```
 var focusEvents = {
            focus: "focusin",
            blur: "focusout"
        },

// bubble to true

  setup: focusEvents[type] ?
                isEventSupported(focusEvents[type]) ?
                function() {
                    var typee = this.type;
                    addDomEventListener(
                        body,
                        focusEvents[typee],
                        function(e) {
                            globalEventListener(e, typee);
                        });
                } :
                function() {
                    addDomEventListener(
                        body,
                        this.type,
                        globalEventListener,
                        true);
                } : null
        };

```

**Comment by jails** [comment]
Ah yeah indeed, looks like `focus` && `blur` event doesn't bubble up. `focusin` and `focusout` would be the perfect solution if they worked on Firefox.
So looks like the only alternative is to set the capture argument to `true` for all kind of events.

**Comment by marcorra** [comment]
I only setting capture to true if not supported. And there are also issues with mouseenter in Firefox, and wheel.

However, I'm using this function I created:

```
 function isEventSupported(type) {
        var eventProp = "on" + type;

        if (eventProp in document) {
            return true;
        }

        var domNode = document.createElement("div");

        domNode.setAttribute(eventProp, "return;");
        if (typeof domNode[eventProp] === "function") {
            return true;
        }

        return type === "wheel" && document.implementation && document.implementation.hasFeature && document.implementation.hasFeature("", "") !== true && document.implementation.hasFeature("Events.wheel", "3.0");
    }
```

Feel free to grab it and improve it if you need it.

**Comment by marcorra** [comment]
Another thing is. Deku as you mentioned before changed from `document.body` to `document` for the root. So `parentNode` are still needed for `document` you think

**Comment by jails** [comment]
Isn't there some events which are not possible to set at a document level ?

**Comment by marcorra** [comment]
Not sure. But seems like all the huge libraries handles it from document. What if a random guy don't set a body tag? Ofc. it will still work except in IE, and it's his fault,but..

**Comment by jails** [comment]
Oh you mean attaching events on `document` doesn't work on IE ?

**Comment by marcorra** [comment]
The whole HTML markup will fall apart in IE to say it easy, and mostly nothing will work. My experience. After you set body and docType in IE things are starting to work.

**Comment by marcorra** [comment]
And when we talk about IE, domLayer in general got a IE issue too. Just to say how stupid IE are. Performance are terrible, but if you switch around so create the node first, then appendChild, and after node are inserted to DOM, you can do render() and IE are happy :)
