### ISSUE TITLE
Any plans for custom event support?

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-event-manager#6]
Hi. Just wonder if you got any plans for adding custom event support? And how it goes with the component library?

**Comment by jails** [comment]
Not sure what you mean by custom event support, it should be already supported.

```js
var eventHandler= function (name, e) {
  console.log(name);
  console.log(e);
};
eventManager = new EventManager(eventHandler);
eventManager.bind('your_custom_event');
// now you can trigger your custom event and it'll be intercepted.
```

**Comment by rickardjanson** [comment]
I was thinking more like this: https://developer.mozilla.org/en/docs/Web/API/CustomEvent

**Comment by jails** [comment]
Custom events are just event with a custom name.
So it works the same way afaik.
Just use `bind()` with your custom event name.
